version: '3'
services:
 download:
  image: ghcr.io/mjtimblin/docker-garmindb:latest
  environment:
   - USERNAME="garmin_username"
   - PASSWORD="garmin_password"
   - STARTDATE="12/31/2019"
   - LATEST=25
   - ALL=1000
  container_name: download-garmindb
  command: ./run_garmin --download --latest --monitoring
  volumes:
   - ./HealthData:/root/HealthData
