version: '3'
services:
  download:
    image: mjtimblin/garmindb:latest
    environment:
    - USERNAME=garmin_username
    - PASSWORD=mypassword
    - STARTDATE=01/01/2019
    # - LATEST=30 # OPTIONAL (DEFAULT: 30)
    # - ALL=5000 # OPTIONAL (DEFAULT: 5000)
    container_name: download-garmindb
    volumes:
    - ./HealthData:/root/HealthData
